name: thenaen_app
description: 더나은호흡 - 호흡재활 앱
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.10.0
  firebase_core: ^3.8.1
  firebase_messaging: ^15.2.1
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.4
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
